set(UTP_VERSION_MAJOR 1 CACHE STRING "libutp major version")
set(UTP_VERSION_MINOR 7 CACHE STRING "libutp minor version")
set(UTP_VERSION_PATCH 1 CACHE STRING "libutp patch version")

set(UTP_VERSION_STRING "${UTP_VERSION_MAJOR}.${UTP_VERSION_MINOR}.${UTP_VERSION_PATCH}")
