function(utp_c_configure_c_test target)
    target_link_libraries(${target} PRIVATE utp_c event_core)
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")
    if(UTP_C_SANITIZER_FLAGS)
        target_compile_options(${target} PRIVATE ${UTP_C_SANITIZER_FLAGS})
        target_link_options(${target} PRIVATE ${UTP_C_SANITIZER_FLAGS})
    endif()
    if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Werror -Wconversion -Wshadow
            -Wstrict-prototypes -Wmissing-prototypes -Wformat=2 -UNDEBUG)
    elseif(MSVC)
        target_compile_options(${target} PRIVATE /utf-8 /W4 /WX /UNDEBUG)
    endif()
    add_test(NAME ${target} COMMAND ${target})
endfunction()

function(utp_c_configure_cpp_test target)
    target_link_libraries(${target} PRIVATE utp_c event_core)
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src" "${CMAKE_CURRENT_SOURCE_DIR}/test"
        "${CMAKE_CURRENT_SOURCE_DIR}/../3rd")
    target_compile_definitions(${target} PRIVATE ${UTP_C_SOCKET_BATCH_DEFINITIONS})
    if(UTP_C_SANITIZER_FLAGS)
        target_compile_options(${target} PRIVATE ${UTP_C_SANITIZER_FLAGS})
        target_link_options(${target} PRIVATE ${UTP_C_SANITIZER_FLAGS})
    endif()
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Werror -Wconversion -Wshadow -Wformat=2 -UNDEBUG)
    elseif(MSVC)
        target_compile_options(${target} PRIVATE /utf-8 /W4 /WX /EHsc /UNDEBUG)
    endif()
    add_test(NAME ${target} COMMAND ${target})
endfunction()

if(BUILD_TESTING AND UTP_C_BUILD_TESTS)
    find_package(Threads REQUIRED)
    add_executable(utp_c_api_test test/test_core.c)
    utp_c_configure_c_test(utp_c_api_test)
    target_include_directories(utp_c_api_test PRIVATE "${UTP_C_GENERATED_INCLUDE_DIR}")
    add_executable(utp_c_public_api_test test/test_public_api.c)
    utp_c_configure_c_test(utp_c_public_api_test)
    target_include_directories(utp_c_public_api_test PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../3rd")
    foreach(test_name IN ITEMS proto crypto receive_history packet_out packet_in send_ledger send_control pending_incoming stream connection congestion minmax bw_sampler bbr mtu nat parser_fuzz transport_integration)
        add_executable(utp_c_${test_name}_test test/test_${test_name}.cc)
        utp_c_configure_cpp_test(utp_c_${test_name}_test)
    endforeach()
    target_link_libraries(utp_c_transport_integration_test PRIVATE Threads::Threads)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND UTP_C_NTRS_EXECUTABLE)
        add_executable(utp_c_ntrs_integration_test test/test_ntrs_integration.cc)
        utp_c_configure_cpp_test(utp_c_ntrs_integration_test)
        set_tests_properties(utp_c_ntrs_integration_test PROPERTIES
            ENVIRONMENT "UTP_C_NTRS_EXECUTABLE=${UTP_C_NTRS_EXECUTABLE}")
    endif()
    if(APPLE)
        add_subdirectory(test/socket_fault)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND UTP_C_SOCKET_BATCH_DEFINITIONS)
        add_subdirectory(test/socket_batch_fault)
    endif()
endif()

if(UTP_C_BUILD_FUZZERS)
    add_executable(utp_c_packet_parser_fuzzer test/fuzz/packet_parser_fuzz.cc)
    target_link_libraries(utp_c_packet_parser_fuzzer PRIVATE utp_c)
    target_include_directories(utp_c_packet_parser_fuzzer PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")
    target_compile_options(utp_c_packet_parser_fuzzer PRIVATE ${UTP_C_FUZZER_FLAGS})
    target_link_options(utp_c_packet_parser_fuzzer PRIVATE ${UTP_C_FUZZER_FLAGS})
    add_custom_target(utp_c_fuzz_packet_parser
        COMMAND $<TARGET_FILE:utp_c_packet_parser_fuzzer> -runs=100000 -max_len=2048
        DEPENDS utp_c_packet_parser_fuzzer
        COMMENT "Running the packet parser libFuzzer target")
endif()

if(UTP_C_BUILD_BENCHMARKS)
    add_executable(utp_c_container_benchmark benchmark/bench_containers.c)
    utp_c_configure_c_test(utp_c_container_benchmark)
    add_executable(utp_c_concurrent_connection_benchmark benchmark/bench_concurrent_connections.c)
    utp_c_configure_c_test(utp_c_concurrent_connection_benchmark)
endif()

if(UTP_C_BUILD_EXAMPLES)
    add_subdirectory(examples)
endif()
