#ifndef EULAR_UTP_INTERNAL_ERROR_H
#define EULAR_UTP_INTERNAL_ERROR_H

#include <stdbool.h>
#include <stdint.h>
#include <utp/status.h>

typedef uint32_t utp_internal_error_t;

#define UTP_INTERNAL_ERROR_OK UINT32_C(0)
#define UTP_INTERNAL_ERROR_FACILITY_INTERNAL UINT32_C(0x10000000)
#define UTP_INTERNAL_ERROR_FACILITY_POSIX UINT32_C(0x20000000)
#define UTP_INTERNAL_ERROR_VALUE_MASK UINT32_C(0x00ffffff)

#define UTP_INTERNAL_ERROR_INVALID_ARGUMENT \
  (UTP_INTERNAL_ERROR_FACILITY_INTERNAL | UINT32_C(1))
#define UTP_INTERNAL_ERROR_NOMEM \
  (UTP_INTERNAL_ERROR_FACILITY_INTERNAL | UINT32_C(2))
#define UTP_INTERNAL_ERROR_LIMIT \
  (UTP_INTERNAL_ERROR_FACILITY_INTERNAL | UINT32_C(3))
#define UTP_INTERNAL_ERROR_EXISTS \
  (UTP_INTERNAL_ERROR_FACILITY_INTERNAL | UINT32_C(4))
#define UTP_INTERNAL_ERROR_NOT_FOUND \
  (UTP_INTERNAL_ERROR_FACILITY_INTERNAL | UINT32_C(5))
#define UTP_INTERNAL_ERROR_OVERFLOW \
  (UTP_INTERNAL_ERROR_FACILITY_INTERNAL | UINT32_C(6))
#define UTP_INTERNAL_ERROR_STATE \
  (UTP_INTERNAL_ERROR_FACILITY_INTERNAL | UINT32_C(7))
#define UTP_INTERNAL_ERROR_PROTOCOL \
  (UTP_INTERNAL_ERROR_FACILITY_INTERNAL | UINT32_C(8))
#define UTP_INTERNAL_ERROR_CRYPTO \
  (UTP_INTERNAL_ERROR_FACILITY_INTERNAL | UINT32_C(9))
#define UTP_INTERNAL_ERROR_AUTH \
  (UTP_INTERNAL_ERROR_FACILITY_INTERNAL | UINT32_C(10))
#define UTP_INTERNAL_ERROR_UNSUPPORTED \
  (UTP_INTERNAL_ERROR_FACILITY_INTERNAL | UINT32_C(11))
#define UTP_INTERNAL_ERROR_TIMEOUT \
  (UTP_INTERNAL_ERROR_FACILITY_INTERNAL | UINT32_C(12))
#define UTP_INTERNAL_ERROR_CLOSED \
  (UTP_INTERNAL_ERROR_FACILITY_INTERNAL | UINT32_C(13))
#define UTP_INTERNAL_ERROR_WOULD_BLOCK \
  (UTP_INTERNAL_ERROR_FACILITY_INTERNAL | UINT32_C(14))
#define UTP_INTERNAL_ERROR_IO \
  (UTP_INTERNAL_ERROR_FACILITY_INTERNAL | UINT32_C(15))

bool utp_internal_error_is_ok(utp_internal_error_t error);
utp_internal_error_t utp_internal_error_from_errno(int system_error);
bool utp_internal_error_is_posix(utp_internal_error_t error);
int utp_internal_error_to_errno(utp_internal_error_t error);
utp_status_t utp_internal_error_to_status(utp_internal_error_t error);

#endif /* EULAR_UTP_INTERNAL_ERROR_H */
