#include <utp/status.h>

const char *utp_status_string(utp_status_t status) {
    switch (status) {
        case UTP_STATUS_OK:
            return "ok";
        case UTP_STATUS_INVALID_ARGUMENT:
            return "invalid_argument";
        case UTP_STATUS_NOMEM:
            return "no_memory";
        case UTP_STATUS_LIMIT:
            return "limit";
        case UTP_STATUS_EXISTS:
            return "exists";
        case UTP_STATUS_NOT_FOUND:
            return "not_found";
        case UTP_STATUS_OVERFLOW:
            return "overflow";
        case UTP_STATUS_STATE:
            return "invalid_state";
        case UTP_STATUS_IO:
            return "io";
        case UTP_STATUS_WOULD_BLOCK:
            return "would_block";
        case UTP_STATUS_TIMEOUT:
            return "timeout";
        case UTP_STATUS_CLOSED:
            return "closed";
        case UTP_STATUS_PROTOCOL:
            return "protocol";
        case UTP_STATUS_CRYPTO:
            return "crypto";
        case UTP_STATUS_AUTH:
            return "authentication";
        case UTP_STATUS_UNSUPPORTED:
            return "unsupported";
        case UTP_STATUS_CANCELLED:
            return "cancelled";
        case UTP_STATUS_BUSY:
            return "busy";
        case UTP_STATUS_IN_PROGRESS:
            return "in_progress";
        case UTP_STATUS_VERSION_MISMATCH:
            return "version_mismatch";
        case UTP_STATUS_SOCKET_OPEN:
            return "socket_open";
        case UTP_STATUS_SOCKET_OPTION:
            return "socket_option";
        case UTP_STATUS_SOCKET_NOT_BOUND:
            return "socket_not_bound";
        case UTP_STATUS_SOCKET_BIND:
            return "socket_bind";
        case UTP_STATUS_SOCKET_IOCTL:
            return "socket_ioctl";
        case UTP_STATUS_SOCKET_READ:
            return "socket_read";
        case UTP_STATUS_SOCKET_WRITE:
            return "socket_write";
        case UTP_STATUS_SOCKET_CONNECTED:
            return "socket_connected";
        case UTP_STATUS_SOCKET_EVENT:
            return "socket_event";
        case UTP_STATUS_STREAM_FLOW_CONTROL:
            return "stream_flow_control";
        case UTP_STATUS_STREAM_DATA_BLOCKED:
            return "stream_data_blocked";
        case UTP_STATUS_STREAM_DATA_LIMITED:
            return "stream_data_limited";
        case UTP_STATUS_STREAM_ID_EXHAUSTED:
            return "stream_id_exhausted";
        case UTP_STATUS_FRAME_FORMAT:
            return "frame_format";
        case UTP_STATUS_FRAME_UNEXPECTED:
            return "frame_unexpected";
        case UTP_STATUS_CRYPTO_UNINITIALIZED:
            return "crypto_uninitialized";
        case UTP_STATUS_CRYPTO_INITIALIZATION:
            return "crypto_initialization";
        case UTP_STATUS_CRYPTO_ENCRYPTION:
            return "crypto_encryption";
        case UTP_STATUS_CRYPTO_DECRYPTION:
            return "crypto_decryption";
        case UTP_STATUS_RANDOM_GENERATION:
            return "random_generation";
        case UTP_STATUS_CONTEXT_UNAVAILABLE:
            return "context_unavailable";
        case UTP_STATUS_CONTEXT_EVENT:
            return "context_event";
        case UTP_STATUS_CONNECTION_HANDSHAKE:
            return "connection_handshake";
        case UTP_STATUS_CONNECTION_CLOSING:
            return "connection_closing";
        case UTP_STATUS_CONNECTION_CID_CONFLICT:
            return "connection_cid_conflict";
        case UTP_STATUS_CONNECTION_STREAM_LIMITED:
            return "connection_stream_limited";
        case UTP_STATUS_CONNECTION_PATH_VALIDATION_BLOCKED:
            return "connection_path_validation_blocked";
        case UTP_STATUS_CONNECTION_SESSION_TOKEN_UNAVAILABLE:
            return "connection_session_token_unavailable";
        case UTP_STATUS_CONNECTION_RESUMPTION_STATE_UNAVAILABLE:
            return "connection_resumption_state_unavailable";
        case UTP_STATUS_RENDEZVOUS_UNAVAILABLE:
            return "rendezvous_unavailable";
        case UTP_STATUS_RENDEZVOUS_REJECTED:
            return "rendezvous_rejected";
        default:
            return "unknown";
    }
}
