if(NOT DEFINED STUN_MUSL_ROOT)
    if(DEFINED ENV{STUN_MUSL_ROOT} AND NOT "$ENV{STUN_MUSL_ROOT}" STREQUAL "")
        set(_stun_musl_root_default "$ENV{STUN_MUSL_ROOT}")
    elseif(DEFINED ENV{MUSL_ROOT} AND NOT "$ENV{MUSL_ROOT}" STREQUAL "")
        set(_stun_musl_root_default "$ENV{MUSL_ROOT}")
    elseif(DEFINED ENV{MUSL_PATH} AND NOT "$ENV{MUSL_PATH}" STREQUAL "")
        set(_stun_musl_root_default "$ENV{MUSL_PATH}")
    else()
        set(_stun_musl_root_default "/opt/musl-toolchain")
    endif()
endif()
set(STUN_MUSL_ROOT "${_stun_musl_root_default}" CACHE PATH "Path to the musl toolchain root.")
unset(_stun_musl_root_default)

if(NOT EXISTS "${STUN_MUSL_ROOT}")
    message(FATAL_ERROR "musl toolchain root does not exist: ${STUN_MUSL_ROOT}")
endif()

if(NOT DEFINED STUN_MUSL_TRIPLE)
    file(GLOB _stun_musl_gcc_candidates
        "${STUN_MUSL_ROOT}/bin/*-gcc"
        "${STUN_MUSL_ROOT}/bin/*-cc"
    )
    if(NOT _stun_musl_gcc_candidates)
        message(FATAL_ERROR "No musl C compiler found under ${STUN_MUSL_ROOT}/bin")
    endif()
    list(SORT _stun_musl_gcc_candidates)
    list(GET _stun_musl_gcc_candidates 0 _stun_musl_cc)
    get_filename_component(_stun_musl_cc_name "${_stun_musl_cc}" NAME)
    string(REGEX REPLACE "-(gcc|cc)$" "" STUN_MUSL_TRIPLE "${_stun_musl_cc_name}")
endif()

set(_stun_musl_bin "${STUN_MUSL_ROOT}/bin")
set(_stun_musl_cc "${_stun_musl_bin}/${STUN_MUSL_TRIPLE}-gcc")
if(NOT EXISTS "${_stun_musl_cc}")
    set(_stun_musl_cc "${_stun_musl_bin}/${STUN_MUSL_TRIPLE}-cc")
endif()
set(_stun_musl_cxx "${_stun_musl_bin}/${STUN_MUSL_TRIPLE}-g++")
if(NOT EXISTS "${_stun_musl_cxx}")
    set(_stun_musl_cxx "${_stun_musl_bin}/${STUN_MUSL_TRIPLE}-c++")
endif()

foreach(_stun_required_tool IN ITEMS "${_stun_musl_cc}" "${_stun_musl_cxx}")
    if(NOT EXISTS "${_stun_required_tool}")
        message(FATAL_ERROR "Required musl tool not found: ${_stun_required_tool}")
    endif()
endforeach()

if(NOT DEFINED CMAKE_SYSTEM_PROCESSOR)
    string(REGEX REPLACE "-.*$" "" CMAKE_SYSTEM_PROCESSOR "${STUN_MUSL_TRIPLE}")
endif()

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER "${_stun_musl_cc}")
set(CMAKE_CXX_COMPILER "${_stun_musl_cxx}")
set(CMAKE_AR "${_stun_musl_bin}/${STUN_MUSL_TRIPLE}-ar" CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB "${_stun_musl_bin}/${STUN_MUSL_TRIPLE}-ranlib" CACHE FILEPATH "" FORCE)
set(CMAKE_STRIP "${_stun_musl_bin}/${STUN_MUSL_TRIPLE}-strip" CACHE FILEPATH "" FORCE)
if(NOT DEFINED CMAKE_SYSROOT)
    set(CMAKE_SYSROOT "${STUN_MUSL_ROOT}/${STUN_MUSL_TRIPLE}")
endif()
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}" "${STUN_MUSL_ROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_EXPORT_NO_PACKAGE_REGISTRY ON CACHE BOOL "" FORCE)
set(CMAKE_FIND_USE_PACKAGE_REGISTRY OFF CACHE BOOL "" FORCE)
set(CMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY ON CACHE BOOL "" FORCE)

set(CMAKE_C_FLAGS_INIT "-static")
set(CMAKE_CXX_FLAGS_INIT "-static")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-static -static-libgcc -static-libstdc++")
