if(NOT DEFINED KCP_MUSL_ROOT)
    if(DEFINED ENV{KCP_MUSL_ROOT} AND NOT "$ENV{KCP_MUSL_ROOT}" STREQUAL "")
        set(_kcp_musl_root_default "$ENV{KCP_MUSL_ROOT}")
    elseif(DEFINED ENV{MUSL_ROOT} AND NOT "$ENV{MUSL_ROOT}" STREQUAL "")
        set(_kcp_musl_root_default "$ENV{MUSL_ROOT}")
    elseif(DEFINED ENV{MUSL_PATH} AND NOT "$ENV{MUSL_PATH}" STREQUAL "")
        set(_kcp_musl_root_default "$ENV{MUSL_PATH}")
    else()
        set(_kcp_musl_root_default "/opt/musl-toolchain")
    endif()
endif()
set(KCP_MUSL_ROOT "${_kcp_musl_root_default}" CACHE PATH "Path to the musl toolchain root.")
unset(_kcp_musl_root_default)

if(NOT EXISTS "${KCP_MUSL_ROOT}")
    message(FATAL_ERROR "musl toolchain root does not exist: ${KCP_MUSL_ROOT}")
endif()

if(NOT DEFINED KCP_MUSL_TRIPLE)
    file(GLOB _kcp_musl_gcc_candidates
        "${KCP_MUSL_ROOT}/bin/*-gcc"
        "${KCP_MUSL_ROOT}/bin/*-cc"
    )
    if(NOT _kcp_musl_gcc_candidates)
        message(FATAL_ERROR "No musl C compiler found under ${KCP_MUSL_ROOT}/bin")
    endif()
    list(SORT _kcp_musl_gcc_candidates)
    list(GET _kcp_musl_gcc_candidates 0 _kcp_musl_cc)
    get_filename_component(_kcp_musl_cc_name "${_kcp_musl_cc}" NAME)
    string(REGEX REPLACE "-(gcc|cc)$" "" KCP_MUSL_TRIPLE "${_kcp_musl_cc_name}")
endif()

set(_kcp_musl_bin "${KCP_MUSL_ROOT}/bin")
set(_kcp_musl_cc "${_kcp_musl_bin}/${KCP_MUSL_TRIPLE}-gcc")
if(NOT EXISTS "${_kcp_musl_cc}")
    set(_kcp_musl_cc "${_kcp_musl_bin}/${KCP_MUSL_TRIPLE}-cc")
endif()
set(_kcp_musl_cxx "${_kcp_musl_bin}/${KCP_MUSL_TRIPLE}-g++")
if(NOT EXISTS "${_kcp_musl_cxx}")
    set(_kcp_musl_cxx "${_kcp_musl_bin}/${KCP_MUSL_TRIPLE}-c++")
endif()

foreach(_kcp_required_tool IN ITEMS "${_kcp_musl_cc}" "${_kcp_musl_cxx}")
    if(NOT EXISTS "${_kcp_required_tool}")
        message(FATAL_ERROR "Required musl tool not found: ${_kcp_required_tool}")
    endif()
endforeach()

if(NOT DEFINED CMAKE_SYSTEM_PROCESSOR)
    string(REGEX REPLACE "-.*$" "" CMAKE_SYSTEM_PROCESSOR "${KCP_MUSL_TRIPLE}")
endif()

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER "${_kcp_musl_cc}")
set(CMAKE_CXX_COMPILER "${_kcp_musl_cxx}")
set(CMAKE_AR "${_kcp_musl_bin}/${KCP_MUSL_TRIPLE}-ar" CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB "${_kcp_musl_bin}/${KCP_MUSL_TRIPLE}-ranlib" CACHE FILEPATH "" FORCE)
set(CMAKE_STRIP "${_kcp_musl_bin}/${KCP_MUSL_TRIPLE}-strip" CACHE FILEPATH "" FORCE)

if(NOT DEFINED CMAKE_SYSROOT)
    set(CMAKE_SYSROOT "${KCP_MUSL_ROOT}/${KCP_MUSL_TRIPLE}")
endif()

set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}" "${KCP_MUSL_ROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_EXPORT_NO_PACKAGE_REGISTRY ON CACHE BOOL "" FORCE)
set(CMAKE_FIND_USE_PACKAGE_REGISTRY OFF CACHE BOOL "" FORCE)
set(CMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY ON CACHE BOOL "" FORCE)

set(CMAKE_C_FLAGS_INIT "-static")
set(CMAKE_CXX_FLAGS_INIT "-static")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-static -static-libgcc -static-libstdc++")
